Personal_Assistant_WEB/Personal_Assistant_WEB/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns, set_language
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('', views.main, name='main'),
    path('contacts/', include('contacts.urls')),
    path('notes/', include('notes.urls')),
    path('users/', include('users.urls')),
    path('news/', include('news.urls')),
    path('filemanager/', include('filemanager.urls')),
    path('set-language/', set_language, name='set_language'),
    path('chat/', include('live_chat.urls')),
    path('profiles/', include('profiles.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Personal_Assistant_WEB/contacts/urls.py
from django.urls import path

from . import views

app_name = 'contacts'

urlpatterns = [
    path("my_contacts/", views.my_contacts, name="my_contacts"),
    path("add_contact/", views.add_contact, name="add_contact"),
    path('edit_contact/<int:contact_id>/', views.edit_contact, name='edit_contact'),
    path('delete_contact/<int:contact_id>/', views.delete_contact, name='delete_contact'),
    path('upcoming_birthdays/', views.upcoming_birthdays, name='upcoming_birthdays')
]

Personal_Assistant_WEB/news/urls.py
from django.urls import path

from . import views

app_name = 'news'

urlpatterns = [
    path('news/', views.news_view, name='news'),
]

Personal_Assistant_WEB/contacts/models.py
from django.contrib.auth.models import User  # noqa
from django.db import models


class Contact(models.Model):
    fullname = models.CharField(max_length=50)
    address = models.CharField(max_length=50, null=False)
    phone = models.CharField(max_length=15, null=False)
    email = models.CharField(max_length=50, null=False)
    birthday = models.DateField(null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    class Meta:
        db_table = "contacts"

Personal_Assistant_WEB/contacts/forms.py
import re
from datetime import date

from django import forms
from django.core.exceptions import ValidationError
from django.forms import DateTimeInput, ModelForm

from .models import Contact


class ContactForm(ModelForm):
    phone = forms.CharField(max_length=15,
                            widget=forms.TextInput(attrs={"class": "form-control", "id": "phoneInput"}),
                            required=True)

    class Meta:
        model = Contact
        fields = ['fullname', 'address', 'phone', 'email', 'birthday']
        widgets = {
            'fullname': forms.TextInput(attrs={"class": "form-control", "id": "fullnameInput"}),
            'address': forms.TextInput(attrs={"class": "form-control", "id": "addressInput"}),
            'email': forms.EmailInput(attrs={"class": "form-control", "id": "emailInput"}),
            'birthday': DateTimeInput(attrs={"class": "form-control", "id": "birthdayInput"}),
        }

    def birthday_validator(self):
        birthday = self.cleaned_data.get('birthday')
        if birthday > date.today():
            raise ValidationError("Birthday cannot be in the future")
        return birthday

    def phone_validator(self):
        phone = self.cleaned_data.get('phone')
        regex = r'^\+?1?\d{9,15}$'
        if not re.match(regex, phone):
            raise ValidationError(
                "Phone number must be entered in the following format: '+111111111'. Up to 15 digits allowed."
            )
        return phone

    def clean(self):
        print("Clean method called")
        cleaned_data = super().clean()
        phone = cleaned_data.get('phone')
        birthday = cleaned_data.get('birthday')
        if phone:
            self.phone_validator()
        if birthday:
            self.birthday_validator()
        return cleaned_data

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.required = True

Personal_Assistant_WEB/contacts/views.py
from datetime import date, timedelta

import cloudinary.uploader
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from Personal_Assistant_WEB.settings import env  # noqa

from .forms import ContactForm
from .models import Contact

cloudinary.config(cloud_name=env('CLOUD_NAME'), api_key=env('CLOUD_API_KEY'), api_secret=env('CLOUD_API_SECRET'))


@login_required
def my_contacts(request):
    contacts = Contact.objects.filter(user=request.user).all() if request.user.is_authenticated else []  # noqa
    query = request.GET.get('q')
    if query:
        contacts = contacts.filter(
            Q(fullname__icontains=query) | Q(email__icontains=query) | Q(phone__icontains=query) | Q(
                address__icontains=query)
        )
    return render(request, 'contacts/my_contacts.html', {"contacts": contacts, "query": query})


@login_required
def add_contact(request):
    form = ContactForm()
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            contact = form.save(commit=False)
            contact.user = request.user
            contact.save()

            return redirect(reverse("contacts:my_contacts"))
    return render(request, "contacts/add_contact.html", context={"form": form})


@login_required
def edit_contact(request, contact_id):
    contact = get_object_or_404(Contact, id=contact_id, user=request.user)
    if request.method == "POST":
        form = ContactForm(request.POST, instance=contact)
        if form.is_valid():
            form.save()
            return redirect(reverse("contacts:my_contacts"))
    else:
        form = ContactForm(instance=contact)
    return render(request, "contacts/edit_contact.html", context={"contact": contact, "form": form})


@login_required
def delete_contact(request, contact_id):
    contact = get_object_or_404(Contact, id=contact_id, user=request.user)
    if request.method == "POST":
        contact.delete()
        return redirect(reverse("contacts:my_contacts"))
    return render(request, "contacts/delete_contact.html", context={"contact": contact})


@login_required
def upcoming_birthdays(request):
    current_date = date.today()
    days = request.GET.get('days', 30)
    try:
        days = int(days)
    except ValueError:
        days = 30
    upcoming = []
    contacts = Contact.objects.filter(user=request.user).all()  # noqa

    for contact in contacts:
        next_birthday = contact.birthday.replace(year=current_date.year)
        if next_birthday < current_date:
            next_birthday = next_birthday.replace(year=current_date.year + 1)

        to_date = current_date + timedelta(days=days)

        if current_date < next_birthday <= to_date:
            if next_birthday.year == current_date.year:
                turning_age = current_date.year - contact.birthday.year
            else:
                turning_age = current_date.year - contact.birthday.year + 1
            days_left_till_birthday = (next_birthday - current_date).days
            upcoming.append((contact, turning_age, days_left_till_birthday))

    upcoming = sorted(upcoming, key=lambda x: x[2])

    return render(request, "contacts/upcoming_birthdays.html", context={"upcoming": upcoming, "days": days})

Personal_Assistant_WEB/contacts/templates/contacts/add_contact.html
{% extends "Personal_Assistant_WEB/base.html" %}
{% load i18n %}

{% block content %}
<div class="container mt-3 ">
    <p class="fs-1 fw-bold">{% trans "Add Contact" %}</p>
    <div class="row">
        <div class="col-xl-8">
            <!-- Account details card-->
            <div class="card mb-4 bg-light">
                <div class="card-header">{% trans "Contact Details" %}</div>
                {% if form.errors and form.non_field_errors %}
                <div class="alert alert-danger" role="alert">
                    {{ form.non_field_errors|safe }}
                </div>
                {% endif %}
                <div class="card-body">
                    <form id="profileForm" action="{% url 'contacts:add_contact' %}" method="post">
                        {% csrf_token %}
                        <!-- Form Group (fullname)-->
                        <div class="mb-3">
                            <label class="small mb-1" for="inputContactFullname">{% trans "Full Name" %}</label>
                            <input class="form-control" id="inputContactFullname" name="fullname" type="text"
                                   placeholder="{% trans " Enter the full name" %}" value="{{ contact.fullname }}">
                            {% if form.fullname.errors %}
                            <p class="text-danger">{{ form.fullname.errors|safe }}</p>
                            {% endif %}
                        </div>
                        <!-- Form Row-->
                        <div class="row gx-3 mb-3">
                            <!-- Form Group (phone)-->
                            <div class="col-md-6">
                                <label class="small mb-1" for="inputContactPhone">{% trans "Phone" %}</label>
                                <input class="form-control" id="inputContactPhone" name="phone" type="tel"
                                       placeholder="{% trans " Enter the phone number" %}" value="{{ contact.phone }}">
                                {% if form.phone.errors %}
                                <p class="text-danger">{{ form.phone.errors|safe }}</p>
                                {% endif %}
                            </div>
                            <!-- Form Group (email)-->
                            <div class="col-md-6">
                                <label class="small mb-1" for="inputContactEmail">{% trans "Email" %}</label>
                                <input class="form-control" id="inputContactEmail" name="email" type="email"
                                       placeholder="{% trans " Enter the email address" %}" value="{{ contact.email }}">
                                {% if form.email.errors %}
                                <p class="text-danger">{{ form.email.errors|safe }}</p>
                                {% endif %}
                            </div>
                        </div>
                        <!-- Form Row-->
                        <div class="row gx-3 mb-3">
                            <!-- Form Group (address)-->
                            <div class="col-md-6">
                                <label class="small mb-1" for="inputContactAddress">{% trans "Address" %}</label>
                                <input class="form-control" id="inputContactAddress" name="address" type="text"
                                       placeholder="{% trans " Enter the address" %}" value="{{ contact.address }}">
                                {% if form.address.errors %}
                                <p class="text-danger">{{ form.address.errors|safe }}</p>
                                {% endif %}
                            </div>
                            <!-- Form Group (birthday)-->
                            <div class="col-md-6">
                                <label class="small mb-1" for="inputContactBirthday">{% trans "Birthday" %}</label>
                                <input class="form-control" id="inputContactBirthday" name="birthday" type="date"
                                       placeholder="{% trans " Enter your birthday" %}" value="{{
                                contact.birthday|date:'Y-m-d' }}">
                                {% if form.birthday.errors %}
                                <p class="text-danger">{{ form.birthday.errors|safe }}</p>
                                {% endif %}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <button class="btn btn-primary ms-1" type="submit">{% trans "Save changes" %}</button>
                            </div>
                            <div class="col text-end">
                                <a href="{% url 'contacts:my_contacts' %}" class="btn btn-secondary">{% trans "Back to Contacts" %}</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Personal_Assistant_WEB/contacts/templates/contacts/delete_contact.html
{% extends "Personal_Assistant_WEB/base.html" %}
{% load i18n %}

{% block content %}
<div class="container mt-3">
    <h1 class="custom-h1">{% trans "Delete Contact" %}</h1>
    <div class="card mb-3">
        <div class="card-header">
            {% trans "Confirm Deletion" %}
        </div>
        <div class="card-body">
            <p class="card-text">{% trans "Are you sure you want to delete the contact" %} "{{ contact.fullname }}"?</p>
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">{% trans "Delete" %}</button>
                <a href="{% url 'contacts:my_contacts' %}" class="btn btn-secondary">{% trans "Cancel" %}</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

Personal_Assistant_WEB/contacts/templates/contacts/edit_contact.html
{% extends "Personal_Assistant_WEB/base.html" %}
{% load i18n %}

{% block content %}
<div class="container-xl mt-4">
    <p class="fs-1 fw-bold">{% trans "Edit Contact" %}</p>
    <div class="row">
        <div class="col-xl-8">
            <!-- Account details card-->
            <div class="card mb-4 bg-light">
                <div class="card-header">{% trans "Contact Details" %}</div>
                {% if form.errors and form.non_field_errors %}
                <div class="alert alert-danger" role="alert">
                    {{ form.non_field_errors|safe }}
                </div>
                {% endif %}
                <div class="card-body">
                    <form id="profileForm" action="{% url 'contacts:edit_contact' contact.id %}" method="post">
                        {% csrf_token %}
                        <!-- Form Group (fullname)-->
                        <div class="mb-3">
                            <label class="small mb-1" for="inputContactFullname">{% trans "Full Name" %}</label>
                            <input class="form-control" id="inputContactFullname" name="fullname" type="text"
                                   placeholder="{% trans "Enter the full name" %}" value="{{ contact.fullname }}">
                            {% if form.fullname.errors %}
                            <p class="text-danger">{{ form.fullname.errors|safe }}</p>
                            {% endif %}
                        </div>
                        <!-- Form Row-->
                        <div class="row gx-3 mb-3">
                            <!-- Form Group (phone)-->
                            <div class="col-md-6">
                                <label class="small mb-1" for="inputContactPhone">{% trans "Phone" %}</label>
                                <input class="form-control" id="inputContactPhone" name="phone" type="tel"
                                       placeholder="{% trans "Enter the phone number" %}" value="{{ contact.phone }}">
                                {% if form.phone.errors %}
                                <p class="text-danger">{{ form.phone.errors|safe }}</p>
                                {% endif %}
                            </div>
                            <!-- Form Group (email)-->
                            <div class="col-md-6">
                                <label class="small mb-1" for="inputContactEmail">{% trans "Email" %}</label>
                                <input class="form-control" id="inputContactEmail" name="email" type="email"
                                       placeholder="{% trans "Enter the email address" %}" value="{{ contact.email }}">
                                {% if form.email.errors %}
                                <p class="text-danger">{{ form.email.errors|safe }}</p>
                                {% endif %}
                            </div>
                        </div>
                        <!-- Form Row-->
                        <div class="row gx-3 mb-3">
                            <!-- Form Group (address)-->
                            <div class="col-md-6">
                                <label class="small mb-1" for="inputContactAddress">{% trans "Address" %}</label>
                                <input class="form-control" id="inputContactAddress" name="address" type="text"
                                       placeholder="{% trans "Enter the address" %}" value="{{ contact.address }}">
                                {% if form.address.errors %}
                                <p class="text-danger">{{ form.address.errors|safe }}</p>
                                {% endif %}
                            </div>
                            <!-- Form Group (birthday)-->
                            <div class="col-md-6">
                                <label class="small mb-1" for="inputContactBirthday">{% trans "Birthday" %}</label>
                                <input class="form-control" id="inputContactBirthday" name="birthday" type="date"
                                       placeholder="{% trans "Enter your birthday" %}" value="{{ contact.birthday|date:'Y-m-d' }}">
                                {% if form.birthday.errors %}
                                <p class="text-danger">{{ form.birthday.errors|safe }}</p>
                                {% endif %}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <button class="btn btn-primary ms-1" type="submit">{% trans "Save changes" %}</button>
                            </div>
                            <div class="col text-end">
                                <a href="{% url 'contacts:my_contacts' %}" class="btn btn-secondary">{% trans "Back to Contacts" %}</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Personal_Assistant_WEB/contacts/templates/contacts/my_contacts.html
{% extends "Personal_Assistant_WEB/base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<div class="row mb-3">
    <div class="col mt-3">
        <h1 class="fs-1 fw-bold">{% trans "Contacts" %}</h1>
    </div>
    {% if not query %}
    <div class="col text-end mt-3">
        <a href="{% url 'contacts:add_contact' %}" class="btn btn-primary">{% trans "Add Contact" %}</a>
        <a href="{% url 'contacts:upcoming_birthdays' %}" class="btn btn-primary ml-2">{% trans "Upcoming Birthdays" %}</a>
    </div>
    {% else %}
    <div class="col text-end mt-3">
        <a href="{% url 'contacts:my_contacts' %}" class="btn btn-secondary">{% trans "Back to Contacts" %}</a>
    </div>
    {% endif %}
</div>
<form class="row g-2 align-items-center search-block" method="GET"
      action="{% url 'contacts:my_contacts' %}">
    <div class="col-auto">
        <input class="form-control" type="search" name="q" placeholder="{% trans 'Search Contacts' %}"
               aria-label="{% trans 'Search' %}">
    </div>
    <div class="col-auto">
        <button class="btn btn-primary" type="submit">{% trans 'Search' %}</button>
    </div>
</form>

<div class="container">
    {% if query %}
    {% if not contacts %}
    <div class="alert alert-danger" role="alert">
        {% trans "We're sorry, but no results were found matching by" %} "{{ query }}". {% trans "Please try again with different keywords or refine your search." %}
    </div>
    {% endif %}
    {% endif %}
    <div class="row">
        {% for contact in contacts %}
        <div class="col-md-6 col-xl-3">
            <div class="card bg-light" style="margin-bottom: 20px; margin-top: 20px;">
                <div class="card-body">
                    <div class="media align-items-center"><span></span>
                        <div class="media-body overflow-hidden text-center">
                            <h3 class="card-text mb-2">{{ contact.fullname }}</h3>
                            <p class="card-text" style="margin-bottom: 30px">
                            <p title="{% trans 'Phone' %}">{% trans 'Phone' %}: {{ contact.phone }}</p>
                            <p title="{% trans 'Email' %}">{% trans 'Email' %}: {{ contact.email }}</p>
                            <p title="{% trans 'Address' %}">{% trans 'Address' %}: {{ contact.address }}</p>
                            <p title="{% trans 'Birthday' %}">{% trans 'Birthday' %}: {{ contact.birthday }}</p>
                            <a href="{% url 'contacts:edit_contact' contact.id %}" class="btn btn-primary">{% trans 'Edit' %}</a>
                            <a href="{% url 'contacts:delete_contact' contact.id %}" class="btn btn-danger">{% trans 'Delete' %}</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

Personal_Assistant_WEB/contacts/templates/contacts/search_results.html
{% extends 'contacts/base.html' %}
{% load static %}


{% block content %}
<h2>Search Results</h2>
{% if query %}
<p>Showing results for: "{{ query }}"</p>
{% endif %}
<div class="notes_list">
    {% for note in results %}
    <div class="note-text" itemscope="" itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">
            {{ forloop.counter }}. {{ note.text }}
        </span>
    </div>
    {% endfor %}
</div>

{% endblock %}

Personal_Assistant_WEB/contacts/templates/contacts/upcoming_birthdays.html
{% extends 'Personal_Assistant_WEB/base.html' %}
{% load i18n %}

{% block content %}
<div class="container mt-3">
    <form id="daysForm" method="GET" action="{% url 'contacts:upcoming_birthdays' %}">
        <label for="daysInput" class="form-label fs-3 mt-3">{% trans "Enter the number of days:" %}</label>
        <input type="number" class="form-control" id="daysInput" name="days" value="{{ days }}" min="1" onchange="this.form.submit()">
    </form>

    <form id="MonthsForm" method="GET" action="{% url 'contacts:upcoming_birthdays' %}">
        <label for="MonthRange" class="form-label fs-3 mt-3">{% trans "or select the month range" %}</label>
        <input type="range" class="form-range" min="30" max="360" step="30" value="{{ days }}" name="days" id="MonthRange" onchange="this.form.submit()">
    </form>

    <p class="fs-4 mt-3">{% trans "Upcoming birthdays in the following" %}
        {{ days }}
        {% trans "day(s)" %}:
    </p>
    <div class="row">
        {% if upcoming %}
        {% for contact, turning_age, days_left_till_birthday in upcoming %}
        <div class="col-md-6 col-xl-3">
            <div class="card bg-light" style="margin-bottom: 20px; margin-top: 20px;">
                <div class="card-body text-center">
                    <div class="media align-items-center"><span></span>
                        <div class="media-body overflow-hidden">
                            <h3 class="card-text mb-2">{{ contact.fullname }}</h3>
                            <p class="card-text" style="margin-bottom: 30px">
                            <p title="{% trans 'Birthday' %}">{% trans 'Birthday' %}: {{ contact.birthday|date:"F j" }}</p>
                            <p title="{% trans 'Days left' %}">{% trans 'Days left' %}: {{ days_left_till_birthday }} {% trans 'day(s)' %}</p>
                            <p title="{% trans 'Turning' %}">{% trans 'Turning' %}: {{ turning_age }} {% trans 'year(s) old' %}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <div class="col mt-5">
            <p>{% trans "No upcoming birthdays." %}</p>
        </div>
        {% endif %}
    </div>
    <div class="col text-end">
        <a href="{% url 'contacts:my_contacts' %}" class="btn btn-secondary">{% trans "Back to Contacts" %}</a>
    </div>
</div>
{% endblock %}