Personal_Assistant_WEB/Personal_Assistant_WEB/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns, set_language
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('', views.main, name='main'),
    path('contacts/', include('contacts.urls')),
    path('notes/', include('notes.urls')),
    path('users/', include('users.urls')),
    path('news/', include('news.urls')),
    path('filemanager/', include('filemanager.urls')),
    path('set-language/', set_language, name='set_language'),
    path('chat/', include('live_chat.urls')),
    path('profiles/', include('profiles.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Personal_Assistant_WEB/contacts/urls.py
from django.urls import path

from . import views

app_name = 'contacts'

urlpatterns = [
    path("my_contacts/", views.my_contacts, name="my_contacts"),
    path("add_contact/", views.add_contact, name="add_contact"),
    path('edit_contact/<int:contact_id>/', views.edit_contact, name='edit_contact'),
    path('delete_contact/<int:contact_id>/', views.delete_contact, name='delete_contact'),
    path('upcoming_birthdays/', views.upcoming_birthdays, name='upcoming_birthdays')
]

Personal_Assistant_WEB/live_chat/urls.py
from django.urls import path

from . import views

app_name = 'live_chat'

urlpatterns = [
    path('', views.chat, name='chat'),
    path("<str:room_name>/", views.room, name="room"),
]

Personal_Assistant_WEB/news/urls.py
from django.urls import path

from . import views

app_name = 'news'

urlpatterns = [
    path('news/', views.news_view, name='news'),
]

Personal_Assistant_WEB/notes/urls.py
from django.urls import path

from . import views

app_name = 'notes'

urlpatterns = [
    path("my_notes/", views.my_notes, name="my_notes"),
    path("add_note/", views.add_note, name="add_note"),
    path('edit_note/<int:note_id>/', views.edit_note, name='edit_note'),
    path('delete_note/<int:note_id>/', views.delete_note, name='delete_note'),
]

Personal_Assistant_WEB/profiles/urls.py
from django.urls import path

from . import views

app_name = 'profiles'

urlpatterns = [

    path("<str:profile_name>/", views.my_profile, name="my_profile"),
    path("<str:profile_name>/edit_profile/", views.edit_profile, name="edit_profile"),
    path('<str:profile_name>/upload_avatar/', views.upload_avatar, name='upload_avatar'),
]

Personal_Assistant_WEB/Personal_Assistant_WEB/views.py
from news.views import news_view  # noqa


def main(request):
    return news_view(request)

Personal_Assistant_WEB/Personal_Assistant_WEB/templates/Personal_Assistant_WEB/base.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% trans "Personal Assistant" %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="icon" href="{% static 'images/favicon.png' %}">
    <link rel="stylesheet" href="{% static 'css/main_page.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" defer></script>
</head>
<body style="background-image: url('{% static 'images/background_2.jpg' %}');">
<div class="d-flex flex-row-reverse">
    <form action="{% url 'set_language' %}" method="post" class="m-0">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ request.path }}">
        <button type="submit" name="language" value="en"
                class="btn btn-link{% if request.LANGUAGE_CODE == 'en' %} active{% endif %}">
            <img src="{% static 'images/flags/uk.png' %}" style="width: 30px; height: 30px"
                 alt="{% trans 'English Flag' %}">
        </button>
    </form>
    <form action="{% url 'set_language' %}" method="post" class="m-0">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ request.path }}">
        <button type="submit" name="language" value="uk"
                class="btn btn-link{% if request.LANGUAGE_CODE == 'uk' %} active{% endif %}">
            <img src="{% static 'images/flags/ua.png' %}" style="width: 30px; height: 30px"
                 alt="{% trans 'Ukrainian Flag' %}">
        </button>
    </form>
</div>
<div class="container-fluid" style="min-height: 100vh;">
    <div class="row header-box pt-3 mb-3">
        <div class="col-md-6">
            <h1 class="my-auto ms-auto custom-title">
                <a href="/" style="text-decoration: none; font-weight: bold;">{% trans "Personal Assistant" %}</a>
            </h1>
        </div>
    </div>
    <main class="container main-container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <button class="navbar-toggler ml-3" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{% trans 'Toggle navigation' %}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="padding-right: 20px;">
                    <li class="nav-item active">
                        <a class="nav-link ml-3" href="{% url 'main' %}"
                           style="margin-left: 12px !important; font-size: 20px">{% trans "Home" %}</a>
                    </li>

                    <!-- Dropdown for Mobile View -->
                    <li class="nav-item dropdown d-lg-none">
                        <a class="nav-link ml-3" href="{% url 'contacts:my_contacts' %}"
                           style="margin-left: 12px !important; font-size: 20px">{% trans "Contacts" %}</a>
                        <a class="nav-link ml-3" href="{% url 'notes:my_notes' %}"
                           style="margin-left: 12px !important; font-size: 20px">{% trans "Notes" %}</a>
                        <a class="nav-link ml-3" href="{% url 'filemanager:my_files' %}"
                           style="margin-left: 12px !important; font-size: 20px">{% trans "Files" %}</a>
                        {% if user.username %}
                        <a class="nav-link ml-3" href="{% url 'profiles:my_profile' user.username %}"
                           style="margin-left: 12px !important; font-size: 20px">{% trans "Profile" %}</a>
                        {% endif %}
                    </li>
                    <!-- End Dropdown for Mobile View -->
                    {% if user.is_authenticated %}
                    <li class="nav-item d-none d-lg-block">
                        <a class="nav-link ml-3" href="{% url 'contacts:my_contacts' %}"
                           style="margin-left: 12px !important;">{% trans "Contacts" %}</a>
                    </li>
                    <li class="nav-item d-none d-lg-block">
                        <a class="nav-link ml-3" href="{% url 'notes:my_notes' %}"
                           style="margin-left: 12px !important;">{% trans "Notes" %}</a>
                    </li>
                    <li class="nav-item d-none d-lg-block">
                        <a class="nav-link ml-3" href="{% url 'filemanager:my_files' %}"
                           style="margin-left: 12px !important;">{% trans "Files" %}</a>
                    </li>
                    {% if user.username %}
                    <li class="nav-item d-none d-lg-block">
                        <a class="nav-link ml-3" href="{% url 'profiles:my_profile' user.username %}"
                           style="margin-left: 12px !important;">{% trans "Profile" %}</a>
                    </li>
                    {% endif %}
                    {% endif %}
                </ul>

                <div class="nav-item d-none d-lg-block" style="padding-right: 20px;">
                    {% if user.is_authenticated %}
                    <a href="/users/logout" class="btn btn-primary">{% trans "Logout" %}</a>
                    {% else %}
                    <a href="/users/signup" class="btn btn-primary">{% trans "SignUp" %}</a>
                    <a href="/users/signin" class="btn btn-primary">{% trans "Login" %}</a>
                    {% endif %}
                    <a href="{% url 'live_chat:chat' %}" class="btn btn-success">{% trans "Live Chat" %}</a>
                </div>
            </div>
        </nav>
        {% block content %} {% endblock %}
    </main>
</div>
</body>
<footer class="bg-body-secondary text-center mt-auto" style="display: flex; justify-content: space-between; align-items: center; height: 50px;">


        <div class="footer-copyright text-start" style="align-self: center">
            {% trans "Copyright ©2024 Project Group 9" %}
            <a class="github-link" href="https://github.com/AndriKovalchuk/DJANGO-PERSONAL-ASSISTANT" style="color: inherit;"
               target="_blank">GitHub</a>
        </div>

        <div class="footer-powered-by text-center">
            {% trans "Powered by" %}
            <a class="django-link" href="https://www.djangoproject.com/" style="color: inherit;" target="_blank">Django</a>
        </div>

        <div class="footer-image-by text-end" >{% trans "Image by jcomp on Freepik" %} </div>


</footer>
</html>