Personal_Assistant_WEB/Personal_Assistant_WEB/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns, set_language
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('', views.main, name='main'),
    path('contacts/', include('contacts.urls')),
    path('notes/', include('notes.urls')),
    path('users/', include('users.urls')),
    path('news/', include('news.urls')),
    path('filemanager/', include('filemanager.urls')),
    path('set-language/', set_language, name='set_language'),
    path('chat/', include('live_chat.urls')),
    path('profiles/', include('profiles.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Personal_Assistant_WEB/filemanager/urls.py
from django.urls import path

from . import views

app_name = 'filemanager'

urlpatterns = [
    path('file/add/', views.upload_file, name='add_file'),
    path('file/view/', views.my_files, name='my_files'),
    path('file/download/<int:file_id>/', views.download_file, name='download_file'),
    path('file/edit/<int:file_id>/', views.edit_file, name='edit_file'),
    path('file/delete/<int:pk>/', views.delete_file, name='delete_file'),

    path('category/add/', views.create_category, name='create_category'),
    path('category/manage/', views.manage_categories, name='manage_categories'),
    path('category/edit/<int:category_id>/', views.edit_category, name='edit_category'),
    path('category/delete/<int:category_id>/', views.delete_category, name='delete_category'),
    path('file/view/<int:category_id>/', views.files_by_categories, name='files_by_categories'),
]

Personal_Assistant_WEB/news/urls.py
from django.urls import path

from . import views

app_name = 'news'

urlpatterns = [
    path('news/', views.news_view, name='news'),
]

Personal_Assistant_WEB/filemanager/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class File(models.Model):
    name = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    url = models.URLField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)

    class Meta:
        db_table = "files"

Personal_Assistant_WEB/filemanager/forms.py
from django import forms

from .models import Category, File


class FileUploadForm(forms.ModelForm):
    file = forms.FileField(widget=forms.ClearableFileInput(attrs={'class': 'form-control mt-1'}))
    category = forms.ModelChoiceField(queryset=Category.objects.none(),  # noqa
                                      widget=forms.Select(attrs={'class': 'form-select mt-1'}))

    def __init__(self, user, *args, **kwargs):
        super(FileUploadForm, self).__init__(*args, **kwargs)
        self.fields['category'].queryset = Category.objects.filter(user=user)  # noqa

    class Meta:
        model = File
        fields = ['file', 'category']


class CategoryForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control mt-1', 'placeholder': 'Category'}))

    class Meta:
        model = Category
        fields = ['name']


class UploadFileForm(forms.Form):
    file = forms.FileField()


class EditFileForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control mt-1', 'placeholder': 'New file name'}))
    category = forms.ModelChoiceField(queryset=Category.objects.none(),  # noqa
                                      widget=forms.Select(attrs={'class': 'form-select mt-1'}),
                                      required=False)

    def __init__(self, user, *args, **kwargs):
        super(EditFileForm, self).__init__(*args, **kwargs)
        self.fields['category'].queryset = Category.objects.filter(user=user)  # noqa

    class Meta:
        model = File
        fields = ['name', 'category']

Personal_Assistant_WEB/filemanager/views.py
import logging
import os

import cloudinary
import cloudinary.uploader
import requests
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from Personal_Assistant_WEB.settings import env  # noqa

from .forms import CategoryForm, EditFileForm, FileUploadForm
from .models import Category, File

cloudinary.config(cloud_name=env('CLOUD_NAME'), api_key=env('CLOUD_API_KEY'), api_secret=env('CLOUD_API_SECRET'))


@login_required
def my_files(request):
    files = File.objects.filter(user=request.user)  # noqa

    if request.GET.get('search'):
        query = request.GET.get('search')
        files = files.filter(Q(name__icontains=query))

    items_per_page = 20
    paginator = Paginator(files, items_per_page)

    page = request.GET.get("page")

    try:
        files_page = paginator.page(page)
    except PageNotAnInteger:
        files_page = paginator.page(1)
    except EmptyPage:
        files_page = paginator.page(paginator.num_pages)

    page_range = range(1, files_page.paginator.num_pages + 1)

    miscellaneous_category, created = Category.objects.get_or_create(name='Miscellaneous', user=request.user)  # noqa

    categories = Category.objects.filter(user=request.user)  # noqa
    return render(request, 'filemanager/my_files.html',
                  {'page_title': 'Your uploaded files', 'files': files_page, 'categories': categories,
                   "page_range": page_range})


@login_required
def upload_file(request):
    if request.method == 'POST':
        form = FileUploadForm(request.user, request.POST, request.FILES)
        if form.is_valid():
            file_to_upload = request.FILES['file']
            file_extension = os.path.splitext(file_to_upload.name)[1].lower()

            if file_extension in ['.mov', '.mp4', '.avi', '.mkv', '.wmv']:
                uploaded_file = cloudinary.uploader.upload(
                    file_to_upload,
                    resource_type="video",
                    folder="uploads/videos/"
                )
                file_url = uploaded_file['secure_url']

            elif file_extension in ['.jpeg', '.jpg', '.png']:
                uploaded_file = cloudinary.uploader.upload(
                    file_to_upload,
                    resource_type="image",
                    folder="uploads/images/"
                )
                file_url = uploaded_file['secure_url']

            elif file_extension in ['.pdf', '.docx', '.xlsx']:
                uploaded_file = cloudinary.uploader.upload(
                    file_to_upload,
                    resource_type="auto",
                    folder="uploads/documents/"
                )
                file_url = uploaded_file['secure_url']

            elif file_extension in ['.mp3', '.wav']:
                uploaded_file = cloudinary.uploader.upload(
                    file_to_upload,
                    resource_type="auto",
                    folder="uploads/audio/"
                )
                file_url = uploaded_file['secure_url']

            else:
                error_message = "Invalid file format. Please upload a video file (MOV, MP4, AVI, MKV, WMV), " \
                                "image file (JPEG, JPG, PNG), document (PDF, DOCX, XLSX) or audio file (MP3, WAV)."
                messages.error(request, error_message)
                return render(request, 'filemanager/add_file.html', {'form': form})

            file_instance = File.objects.create(  # noqa
                user=request.user,
                url=file_url,
                name=file_to_upload.name,
            )

            if form.cleaned_data['category']:
                file_instance.category = form.cleaned_data['category']
            else:
                new_category = form.cleaned_data.get('new_category')
                if new_category:
                    # Creating a new category
                    category = Category.objects.create(name=new_category, user=request.user)  # noqa
                    file_instance.category = category

            file_instance.save()

            return redirect('filemanager:my_files')
    else:
        form = FileUploadForm(user=request.user)

    return render(request, 'filemanager/add_file.html', {'page_title': 'Upload File', 'form': form})


@login_required
def files_by_categories(request, category_id):
    files = File.objects.filter(category_id=category_id)  # noqa

    items_per_page = 20
    paginator = Paginator(files, items_per_page)

    page = request.GET.get("page")

    try:
        files_page = paginator.page(page)
    except PageNotAnInteger:
        files_page = paginator.page(1)
    except EmptyPage:
        files_page = paginator.page(paginator.num_pages)

    page_range = range(1, files_page.paginator.num_pages + 1)

    category = get_object_or_404(Category, pk=category_id)
    categories = Category.objects.filter(user=request.user)  # noqa
    return render(request, 'filemanager/my_files.html',
                  {'page_title': f'Files by "{category.name}"', 'files': files_page, 'categories': categories,
                   "page_range": page_range})


@login_required
def edit_file(request, file_id):
    file_instance = get_object_or_404(File, pk=file_id)

    if request.method == 'POST':
        form = EditFileForm(request.user, request.POST, instance=file_instance)

        if form.is_valid():
            form.save()
            return redirect('filemanager:my_files')
    else:
        form = EditFileForm(request.user, instance=file_instance)

    return render(request, 'filemanager/edit_file.html',
                  {'page_title': 'Edit File', 'form': form, 'file': file_instance})


@login_required
def download_file(file_id):
    file_instance = get_object_or_404(File, pk=file_id)
    try:

        file_url, options = cloudinary.utils.cloudinary_url(file_instance.url)

        response = requests.get(file_url)

        if response.status_code == 200:

            file_content = response.content
            http_response = HttpResponse(file_content, content_type='application/octet-stream')
            http_response['Content-Disposition'] = f'attachment; filename="{file_instance.name}"'
            return http_response
        else:
            return HttpResponse("Failed to download file", status=response.status_code)

    except Exception as e:
        print(f'Failed to download file: {e}')
        return HttpResponse("Failed to download file", status=500)


@login_required
def delete_file(request, pk):
    file_instance = get_object_or_404(File, pk=pk)
    file_url = file_instance.url

    if request.method == 'POST':
        try:
            file_instance.delete()
            if file_url:
                public_id = file_url.split('/')[-1].split('.')[0]
                logging.info(f'Public ID extracted: {public_id}')
                result = cloudinary.uploader.destroy(public_id)
                logging.info(f'Result from Cloudinary: {result}')
            else:
                logging.warning('File URL is empty.')
        except Exception as e:
            logging.error(f'Failed to delete file from Cloudinary: {e}')
            return render(request, 'error.html', {'error_message': 'Failed to delete file. Please try again later.'})

        return redirect('filemanager:my_files')

    return render(request, 'filemanager/delete_file.html',
                  context={'page_title': 'Delete File',
                           "form_action": reverse("filemanager:delete_file", args=[file_instance.pk]),
                           "back_list": reverse("filemanager:my_files"),
                           'type': 'file',
                           'name': file_instance.name
                           })


@login_required
def create_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            category = form.save(commit=False)
            category.user = request.user
            category.save()
            return redirect('filemanager:my_files')
    else:
        form = CategoryForm()
    miscellaneous_category, created = Category.objects.get_or_create(name='Miscellaneous', user=request.user)  # noqa

    return render(request, 'filemanager/create_category.html', {'page_title': 'Create Category', 'form': form})


@login_required
def manage_categories(request):
    categories = Category.objects.filter(user=request.user)  # noqa
    return render(request, 'filemanager/manage_categories.html',
                  {'page_title': 'Manage Categories', 'categories': categories})


@login_required
def edit_category(request, category_id):
    category = Category.objects.get(pk=category_id)  # noqa
    if request.method == 'POST':
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            return redirect('filemanager:manage_categories')
    else:
        form = CategoryForm(instance=category)

    return render(request, 'filemanager/create_category.html',
                  {'page_title': 'Edit Category', 'category': category, 'form': form})


@login_required
def delete_category(request, category_id):
    category = get_object_or_404(Category, pk=category_id)

    if request.method == 'POST':
        uncategorized = Category.objects.filter(name='Без категорії', user=request.user).first()  # noqa
        files = File.objects.filter(category=category)  # noqa
        files.update(category=uncategorized)
        category.delete()
        return redirect('filemanager:manage_categories')

    return render(request, 'filemanager/delete_file.html',
                  context={'page_title': 'Delete Category',

Personal_Assistant_WEB/filemanager/templates/filemanager/add_file.html
{% extends 'Personal_Assistant_WEB/base.html' %}
{% load i18n %}
{% block title %}{{ page_title }}{% endblock %}

{% block content %}
<div class="row mb-3">
    <div class="col mt-3">
        <h1 class="fs-1 fw-bold">{% trans page_title %}</h1>
    </div>
    <div class="col text-end mt-3">
        <a href="{% url 'filemanager:create_category' %}" class="btn btn-primary">{% trans "Create Category" %}</a>
        <a href="{% url 'filemanager:my_files' %}" class="btn btn-secondary">{% trans "Back to File List" %}</a>
    </div>
</div>
{% if messages %}
<div class="alert alert-danger" role="alert">
    {% for message in messages %}
    {{ message }}
    {% endfor %}
</div>
{% endif %}
<div class="row">
    <div class="col-md-6">
        <div class="card bg-light">
            <form action="{% if file %}{% url 'filemanager:edit_file' file.id %}{% else %}{% url 'filemanager:add_file' %}{% endif %}"
                  method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="card-body">
                    {{ form.as_p }}
                </div>
                <div class="card-footer">
                    <button class="btn btn-primary" type="submit">{% trans "Upload" %}</button>
                    <button class="btn btn-secondary" type="reset">{% trans "Reset" %}</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

Personal_Assistant_WEB/filemanager/templates/filemanager/create_category.html
{% extends 'Personal_Assistant_WEB/base.html' %}
{% load i18n %}
{% block title %}{{ page_title }}{% endblock %}

{% block content %}
<div class="row mb-3">
    <div class="col mt-3">
        <h1 class="fs-1 fw-bold">{% trans page_title %}</h1>
    </div>
    <div class="col text-end mt-3">
        <a href="{% url 'filemanager:my_files' %}" class="btn btn-primary">{% trans "Back to File List" %}</a>
        <a href="{% url 'filemanager:manage_categories' %}" class="btn btn-secondary">{% trans "Back to Category List" %}</a>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="card">
            <form action="{% if category %}{% url 'filemanager:edit_category' category.id %}{% else %}{% url 'filemanager:create_category' %}{% endif %}" method="post">
                {% csrf_token %}
                <div class="card-body">

                    {{ form.as_p }}
                </div>
                <div class="card-footer">
                    <button class="btn btn-primary" type="submit">{% trans "Save" %}</button>
                    <button class="btn btn-secondary" type="reset">{% trans "Reset" %}</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

Personal_Assistant_WEB/filemanager/templates/filemanager/edit_file.html
{% extends 'Personal_Assistant_WEB/base.html' %}
{% load i18n %}
{% block title %}{{ page_title }}{% endblock %}

{% block content %}
<div class="row mb-3">
    <div class="col mt-3">
        <h1 class="fs-1 fw-bold">{% trans page_title %}</h1>
    </div>
    <div class="col text-end mt-3">
        <a href="{% url 'filemanager:my_files' %}" class="btn btn-primary">{% trans "Back to File List" %}</a>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="card">
            <form action="{% url 'filemanager:edit_file' file.id %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="card-body">
                    {{ form.as_p }}
                </div>
                <div class="card-footer">
                    <button class="btn btn-primary" type="submit">{% trans "Save Changes" %}</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

Personal_Assistant_WEB/filemanager/templates/filemanager/manage_categories.html
{% extends 'Personal_Assistant_WEB/base.html' %}
{% load i18n %}

{% block title %}{{ page_title }}{% endblock %}

{% block content %}
<div class="row mb-3">
    <div class="col mt-3">
        <h1 class="fs-1 fw-bold">{% trans page_title %}</h1>
    </div>
    <div class="col text-end mt-3">
        <a href="{% url 'filemanager:create_category' %}" class="btn btn-primary">{% trans "Add Category" %}</a>
        <a href="{% url 'filemanager:my_files' %}" class="btn btn-secondary">{% trans "Back to Files" %}</a>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card mb-4">
            <div class="card-body">
                {% if categories %}
                <table class="table m-0">
                    <thead>
                    <tr>
                        <th scope="col">{% trans "Category" %}</th>
                        <th scope="col">{% trans "Actions" %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for category in categories %}
                    <tr>
                        <td>
                            <a class="h6" href="{% url 'filemanager:files_by_categories' category.id %}">{{ category.name }}</a>
                        </td>
                        <td>
                            <div class="d-inline-flex gap-2">
                                <a href="{% url 'filemanager:edit_category' category.id %}"
                                   class="btn btn-sm btn-primary">{% trans "Edit" %}</a>
                                <a href="{% url 'filemanager:delete_category' category.id %}"
                                   class="btn btn-sm btn-danger">{% trans "Delete" %}</a>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
                {% else %}
                <p class="h5 m-0">{% trans "You don't have any files. Please add a category to start organizing your documents." %}</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

Personal_Assistant_WEB/filemanager/templates/filemanager/my_files.html
{% extends 'Personal_Assistant_WEB/base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
<div class="row mb-3">
    <div class="col mt-3">
        <h1 class="fs-1 fw-bold">{% trans page_title %}</h1>
    </div>
    <div class="col text-end mt-3">
        <a href="{% url 'filemanager:add_file' %}" class="btn btn-primary">{% trans "Add file" %}</a>
        <a href="{% url 'filemanager:create_category' %}" class="btn btn-primary">{% trans "Add Category" %}</a>
    </div>
</div>
<div class="row">
    <div class="col-md-3">
        <div class="card mb-4">
            <div class="card-header">
                <h2 class="h4 m-0">{% trans "Search File" %}</h2>
            </div>
            <div class="card-body">
                <form action="{% url 'filemanager:my_files' %}" method="get">
                    <div class="d-flex gap-2">
                        <input type="search" class="form-control" id="search" name="search" placeholder="{% trans "File name" %}">
                        <button class="btn btn-sm btn-primary" type="submit">{% trans "Search" %}</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="card">
            <div class="card-header">
                <h2 class="h4 m-0">{% trans "Categories" %}</h2>
            </div>
            <div class="card-body">
                <div class="list-group">
                    <a href="{% url 'filemanager:my_files' %}"
                       class="list-group-item list-group-item-action {% if request.resolver_match.url_name != 'files_by_categories' %}active{% endif %}"
                       aria-current="true">
                        {% trans "All files" %}
                    </a>
                    {% for category in categories %}
                    <a href="{% url 'filemanager:files_by_categories' category.id %}"
                       class="list-group-item list-group-item-action {% if request.resolver_match.url_name == 'files_by_categories' and request.resolver_match.kwargs.category_id == category.id %} active{% endif %}">
                        {{ category.name }}
                    </a>
                    {% endfor %}
                </div>
            </div>
            <div class="card-footer">
                <a class="btn btn-link p-0" href="{% url 'filemanager:manage_categories' %}">{% trans "Manage Categories" %}</a>
            </div>
        </div>
    </div>
    <div class="col-md-9">
        <div class="card mb-4">
            <div class="card-body">
                {% if files %}
                <table class="table m-0">
                    <thead>
                    <tr>
                        <th scope="col">{% trans "File name" %}</th>
                        <th scope="col" class="text-end">{% trans "Actions" %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for file in files %}
                    <tr>
                        <td class="align-middle">
                            <a href="{{ file.url }}" target="_blank">{{ file.name }}</a>
                            <a href="{% url 'filemanager:download_file' file.id %}" download="{{ file.name }}">
                                <img src="{% static 'images/download.svg' %}"
                                     style="height: 20px; width: 20px; margin-left: 10px;" alt="{% trans "Download Icon" %}">
                            </a>
                        </td>
                        <td class="align-middle">
                            <div class="d-flex justify-content-end">
                                <a href="{% url 'filemanager:edit_file' file.id %}" class="btn btn-sm btn-primary me-2">{% trans "Edit" %}</a>
                                <a href="{% url 'filemanager:delete_file' file.id %}" class="btn btn-sm btn-danger">{% trans "Delete" %}</a>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
                {% else %}
                <p class="h5 m-0">{% trans "You don't have any files. Please download a file to start organizing your documents." %}</p>
                {% endif %}
            </div>
            {% if files.paginator.num_pages > 1 %}
            <div class="card-footer">
                <nav aria-label="Page navigation example">
                    <ul class="pagination m-0">
                        {% if files.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page={{ files.previous_page_number }}">{% trans "Previous" %}</a>
                        </li>
                        {% endif %}
                        {% for number in page_range %}
                        {% if number != files.number %}
                        <li class="page-item"><a class="page-link" href="?page={{ number }}">{{ number }}</a></li>
                        {% else %}
                        <li class="page-item"><a class="page-link">{{ number }}</a></li>
                        {% endif %}
                        {% endfor %}
                        {% if files.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ files.next_page_number }}">{% trans "Next" %}</a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

Personal_Assistant_WEB/filemanager/templates/filemanager/uploaded_files.html
{% extends 'contacts/base.html' %}

{% block title %}{{ page_title }}{% endblock %}

{% block content %}
<div class="row mb-3">
    <div class="col">
        <h1 class="card-title h3">{{ page_title }}</h1>
    </div>
    <div class="col text-end">
        <a href="{% url 'filemanager:add_file' %}" class="btn btn-primary">Add file</a>
        <a href="{% url 'filemanager:create_category' %}" class="btn btn-outline-secondary">Add Category</a>
    </div>
</div>
<div class="row">
    <div class="col-md-3">
        <div class="card mb-4">
            <div class="card-header">
                <h2 class="h4 m-0">Search File</h2>
            </div>
            <div class="card-body">
                <form action="{% url 'filemanager:uploaded_files' %}" method="get">
                    <div class="d-flex gap-2">
                        <input type="search" class="form-control" id="search" name="search" placeholder="File name">
                        <button class="btn btn-sm btn-primary" type="submit">Search</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="card">
            <div class="card-header">
                <h2 class="h4 m-0">Categories</h2>
            </div>
            <div class="card-body">
                <div class="list-group">
                    <a href="{% url 'filemanager:uploaded_files' %}"
                       class="list-group-item list-group-item-action {% if request.resolver_match.url_name != 'files_by_categories' %}active{% endif %}"
                       aria-current="true">
                        All files
                    </a>
                    {% for category in categories %}
                    <a href="{% url 'filemanager:files_by_categories' category.id %}"
                       class="list-group-item list-group-item-action {% if request.resolver_match.url_name == 'files_by_categories' and request.resolver_match.kwargs.category_id == category.id %} active{% endif %}">
                        {{ category.name }}
                    </a>
                    {% endfor %}
                </div>
            </div>
            <div class="card-footer">
                <a class="btn btn-link p-0" href="{% url 'filemanager:manage_categories' %}">Manage Categories</a>
            </div>
        </div>
    </div>
    <div class="col-md-9">
        <div class="card mb-4">
            <div class="card-body">
                {% if files %}
                <table class="table m-0">
                    <thead>
                    <tr>
                        <th scope="col">File name</th>
                        <th scope="col">Category</th>
                        <th scope="col">Actions</th>
                    </tr>
                    </thead>
                    <tbody>

                    {% for file in files %}
                    <tr>
                        <td><a href="{% url 'filemanager:download_file' file.id %}" download="{{file.file.name}}">{{file.file.name}}</a>
                        </td>
                        <td>{{file.category}}</td>
                        <td>
                            <div class="d-inline-flex gap-2">
                                <a href="{% url 'filemanager:edit_file' file.id %}"
                                   class="btn btn-sm btn-primary">Edit</a>
                                <a href="{% url 'filemanager:delete_file' file.id %}"
                                   class="btn btn-sm btn-danger">Delete</a>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}

                    </tbody>
                </table>
                {% else %}
                <p class="h5 m-0">You don't have files. Upload one.</p>
                {% endif %}
            </div>
            {% if files.paginator.num_pages > 1 %}
            <div class="card-footer">
                <nav aria-label="Page navigation example">
                    <ul class="pagination m-0">
                        {% if files.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page={{ files.previous_page_number }}">Previous</a></li>
                        {% endif %}
                        {% for number in page_range %}
                        {% if number != files.number %}
                        <li class="page-item"><a class="page-link" href="?page={{ number }}">{{ number }}</a></li>
                        {% else %}
                        <li class="page-item"><a class="page-link">{{ number }}</a></li>
                        {% endif %}
                        {% endfor %}
                        {% if files.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ files.next_page_number }}">Next</a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}