Personal_Assistant_WEB/Personal_Assistant_WEB/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns, set_language
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('', views.main, name='main'),
    path('contacts/', include('contacts.urls')),
    path('notes/', include('notes.urls')),
    path('users/', include('users.urls')),
    path('news/', include('news.urls')),
    path('filemanager/', include('filemanager.urls')),
    path('set-language/', set_language, name='set_language'),
    path('chat/', include('live_chat.urls')),
    path('profiles/', include('profiles.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Personal_Assistant_WEB/contacts/urls.py
from django.urls import path

from . import views

app_name = 'contacts'

urlpatterns = [
    path("my_contacts/", views.my_contacts, name="my_contacts"),
    path("add_contact/", views.add_contact, name="add_contact"),
    path('edit_contact/<int:contact_id>/', views.edit_contact, name='edit_contact'),
    path('delete_contact/<int:contact_id>/', views.delete_contact, name='delete_contact'),
    path('upcoming_birthdays/', views.upcoming_birthdays, name='upcoming_birthdays')
]

Personal_Assistant_WEB/news/urls.py
from django.urls import path

from . import views

app_name = 'news'

urlpatterns = [
    path('news/', views.news_view, name='news'),
]

Personal_Assistant_WEB/notes/urls.py
from django.urls import path

from . import views

app_name = 'notes'

urlpatterns = [
    path("my_notes/", views.my_notes, name="my_notes"),
    path("add_note/", views.add_note, name="add_note"),
    path('edit_note/<int:note_id>/', views.edit_note, name='edit_note'),
    path('delete_note/<int:note_id>/', views.delete_note, name='delete_note'),
]

Personal_Assistant_WEB/notes/models.py
from django.contrib.auth.models import User  # noqa
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=25, null=False, unique=True)

    class Meta:
        db_table = "tags"


class Note(models.Model):
    text = models.CharField(null=False)
    description = models.CharField(null=False)
    created = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField(Tag)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    class Meta:
        db_table = "notes"

Personal_Assistant_WEB/notes/forms.py
from django import forms

from .models import Note


class NoteForm(forms.ModelForm):
    tags = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control", "id": "tagsInput"}))

    class Meta:
        model = Note
        fields = ['text', 'description', 'tags']
        widgets = {
            'text': forms.TextInput(attrs={"class": "form-control", "id": "textInput"}),
            'description': forms.TextInput(attrs={"class": "form-control", "id": "descriptionInput"}),
            'tags': forms.TextInput(attrs={"class": "form-control", "id": "tagInput"})
        }

    def clean_tags(self):
        tags_input = self.cleaned_data['tags']
        if tags_input:
            return tags_input
        else:
            return ""

Personal_Assistant_WEB/notes/views.py
import cloudinary.uploader
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Q
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from notes.forms import NoteForm  # noqa
from notes.models import Note, Tag  # noqa

from Personal_Assistant_WEB.settings import env  # noqa

cloudinary.config(cloud_name=env('CLOUD_NAME'), api_key=env('CLOUD_API_KEY'), api_secret=env('CLOUD_API_SECRET'))


@login_required
def my_notes(request):
    notes = Note.objects.filter(user=request.user).all()  # noqa
    tag = request.GET.get('tag')
    query = request.GET.get('q')
    if tag:
        notes = notes.filter(tags__name__icontains=tag)
    if query:
        notes = notes.filter(Q(text__icontains=query) | Q(tags__name__icontains=query))
    top_tags = Tag.objects.filter(note__user=request.user).annotate(count=Count('note')).order_by('-count')[:10]
    return render(request, "notes/my_notes.html", context={"notes": notes, "top_tags": top_tags, 'query': query, "tag": tag})


@login_required
def add_note(request):
    form = NoteForm()
    if request.method == "POST":
        form = NoteForm(request.POST)
        if form.is_valid():
            text = form.cleaned_data['text']
            description = form.cleaned_data['description']
            tags_input = form.cleaned_data['tags']

            new_note = Note.objects.create(
                text=text,
                description=description,
                user=request.user,
            )
            tags_list = [tag.strip() for tag in tags_input.split(',') if tag.strip()]
            for tag_name in tags_list:
                tag, _ = Tag.objects.get_or_create(name=tag_name)
                new_note.tags.add(tag)
            return redirect(reverse("notes:my_notes"))
    return render(request, "notes/add_note.html", context={"form": form})


@login_required
def edit_note(request, note_id):
    note = get_object_or_404(Note, id=note_id, user=request.user)
    if request.method == "POST":
        form = NoteForm(request.POST, instance=note)
        if form.is_valid():
            text = form.cleaned_data['text']
            description = form.cleaned_data['description']
            tags_input = form.cleaned_data['tags']

            note.text = text
            note.description = description
            note.save()

            tags_list = [tag.strip() for tag in tags_input.split(',') if tag.strip()]
            existing_tags = note.tags.all()

            for tag in existing_tags:
                if tag.name not in tags_list:
                    note.tags.remove(tag)

            for tag_name in tags_list:
                tag, _ = Tag.objects.get_or_create(name=tag_name)
                note.tags.add(tag)

            Tag.objects.filter(note=None).delete()

            return redirect("notes:my_notes")
    else:
        form = NoteForm(instance=note)
    return render(request, "notes/edit_note.html", {"form": form, "note": note})


@login_required
def delete_note(request, note_id):
    note = get_object_or_404(Note, id=note_id, user=request.user)
    if request.method == "POST":
        tags_to_delete = list(note.tags.all())
        note.delete()
        for tag in tags_to_delete:
            if tag.note_set.count() == 0:
                tag.delete()
        return redirect(reverse("notes:my_notes"))
    return render(request, "notes/delete_note.html", context={"note": note})

Personal_Assistant_WEB/notes/templates/notes/add_note.html
{% extends "Personal_Assistant_WEB/base.html" %}
{% load i18n %}

{% block content %}
<div class="container mt-3 ">
    <p class="fs-1 fw-bold">{% trans "Add Note" %}</p>
    <div class="row">
        <div class="col-xl-8">
            <!-- Note details card-->
            <div class="card mb-4 bg-light">
                <div class="card-header">{% trans "Note Details" %}</div>
                {% if form.errors %}
                <div class="alert alert-danger" role="alert">
                    {% for field, errors in form.errors.items %}
                        {% for error in errors %}
                            {{ error }}
                        {% endfor %}
                    {% endfor %}
                </div>
                {% endif %}
                <div class="card-body">
                    <form id="noteForm" action="{% url 'notes:add_note' %}" method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="row">
                            <div class="col">
                                <button class="btn btn-primary ms-1" type="submit">{% trans "Save changes" %}</button>
                            </div>
                            <div class="col text-end">
                                <a href="{% url 'notes:my_notes' %}" class="btn btn-secondary">{% trans "Back to Notes" %}</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Personal_Assistant_WEB/notes/templates/notes/delete_note.html
{% extends "Personal_Assistant_WEB/base.html" %}
{% load i18n %}

{% block content %}
<div class="container mt-3">
    <h1 class="custom-h1">{% trans "Delete Note" %}</h1>
    <div class="card mb-3">
        <div class="card-header">
            {% trans "Confirm Deletion" %}
        </div>
        <div class="card-body">
            <p class="card-text">{% trans "Are you sure you want to delete the note" %} "{{ note.text }}"?</p>
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">{% trans "Delete" %}</button>
                <a href="{% url 'notes:my_notes' %}" class="btn btn-secondary">{% trans "Cancel" %}</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

Personal_Assistant_WEB/notes/templates/notes/edit_note.html
{% extends "Personal_Assistant_WEB/base.html" %}
{% load i18n %}
{% block content %}
<div class="container-xl mt-4">
    <p class="fs-1 fw-bold">{% trans "Edit Note" %}</p>
    <div class="row">
        <div class="col-xl-8">
            <!-- Note details card-->
            <div class="card mb-4 bg-light">
                <div class="card-header">{% trans "Note Details" %}</div>
                {% if form.errors %}
                <div class="alert alert-danger" role="alert">
                    {% for field, errors in form.errors.items %}
                        {% for error in errors %}
                            {{ error }}
                        {% endfor %}
                    {% endfor %}
                </div>
                {% endif %}
                <div class="card-body">
                    <form id="profileForm" action="{% url 'notes:edit_note' note.id %}" method="post">
                        {% csrf_token %}
                        <!-- Form Group (text)-->
                        <div class="mb-3">
                            <label class="small mb-1" for="inputNoteText">{% trans "Text" %}</label>
                            <input class="form-control" id="inputNoteText" name="text" type="text"
                                   placeholder="{% trans "Enter the text" %}" value="{{ note.text }}">
                            {% if form.text.errors %}
                            <p class="text-danger">{{ form.text.errors }}</p>
                            {% endif %}
                        </div>
                        <!-- Form Group (description)-->
                        <div class="mb-3">
                            <label class="small mb-1" for="inputNoteDescription">{% trans "Description" %}</label>
                            <input class="form-control" id="inputNoteDescription" name="description" type="text"
                                   placeholder="{% trans "Enter the description" %}" value="{{ note.description }}">
                            {% if form.description.errors %}
                            <p class="text-danger">{{ form.description.errors }}</p>
                            {% endif %}
                        </div>
                        <!-- Form Group (tags)-->
                        <div class="mb-3">
                            <label class="small mb-1" for="InputNoteTags">{% trans "Tags" %}</label>
                            <input class="form-control" id="InputNoteTags" name="tags" type="text"
                                   placeholder="{% trans "Enter the tags" %}" value="{% for tag in note.tags.all %}{{ tag.name }}{% if not forloop.last %}, {% endif %}{% endfor %}">
                            {% if form.tags.errors %}
                            <p class="text-danger">{{ form.tags.errors }}</p>
                            {% endif %}
                        </div>
                        <div class="row">
                            <div class="col">
                                <button class="btn btn-primary ms-1" type="submit">{% trans "Save changes" %}</button>
                            </div>
                            <div class="col text-end">
                                <a href="{% url 'contacts:my_contacts' %}" class="btn btn-secondary">{% trans "Back to Contacts" %}</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Personal_Assistant_WEB/notes/templates/notes/my_notes.html
{% extends "Personal_Assistant_WEB/base.html" %}
{% load i18n %}
{% load static %}
{% block content %}
<div class="row mb-3">
    <link rel="stylesheet" href="{% static 'css/notes.css' %}">
    <div class="col mt-3">
        <h1 class="fs-1 fw-bold">{% trans "My Notes" %}</h1>
    </div>
    {% if query or tag %}
    <div class="col text-end mt-3">
        <a href="{% url 'notes:my_notes' %}" class="btn btn-secondary">Back to Notes</a>
    </div>
    {% else %}
    <div class="col text-end mt-3">
        <a href="{% url 'notes:add_note' %}" class="btn btn-primary">{% trans 'Add Note' %}</a>
    </div>
    {% endif %}

</div>
<form class="row g-2 align-items-center search-block" style="margin-bottom: -35px; " method="GET"
      action="{% url 'notes:my_notes' %}">
    <div class="col-auto">
        <input class="form-control" type="search" name="q" placeholder="{% trans 'Search Notes' %}"
               aria-label="{% trans 'Search' %}">
    </div>
    <div class="col-auto">
        <button class="btn btn-primary" type="submit">{% trans 'Search' %}</button>
    </div>

</form>
<div style="width: 300px; float: right; margin-top: -43px">
    <div class="col align-items-right order-first order-md-last">
        <!-- Displaying top 10 tags -->
        <div class="mb-3">
            <h3 class="mb-3 justify-content-between text-end top-ten">{% trans 'Top 10 Tags' %}</h3>
            <ul class="list-group">
                {% for tag in top_tags %}
                <li class="list-group-item justify-content-between text-end top-tags">
                        <span class="badge rounded-pill text-bg-primary">
                            <a href="?tag={{ tag.name }}"># {{ tag.name }} ({{ tag.count }})</a>
                        </span>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% if query %}
{% if not notes %}
<div class="alert alert-danger" role="alert">
    {% trans "We're sorry, but no results were found matching by" %} "{{ query }}". {% trans "Please try again with
    different keywords or refine your search." %}
</div>
{% endif %}
{% endif %}
<div class="row">
    <div class="col-mb-9" style="margin-top: 55px">
        {% for note in notes %}
        <div class="card mb-3">
            <div class="card-header">
                {{ forloop.counter }}. {{ note.text }}
            </div>
            <div class="card-body bg-light">
                <p class="card-text desc">{% trans 'Description' %}: {{ note.description }}</p>
                <p class="card-text">{% trans 'Tags' %}:
                    {% for tag in note.tags.all %}
                    #{{ tag.name }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </p>

                <a href="{% url 'notes:edit_note' note.id %}" class="btn btn-primary">{% trans 'Edit' %} </a>
                <a href="{% url 'notes:delete_note' note.id %}" class="btn btn-danger">{% trans 'Delete' %}</a>
                <!-- Button to open modal window for this note -->
                <button type="button" class="btn btn-primary justify-content-end" data-bs-toggle="modal"
                        data-bs-target="#noteModal{{ note.id }}">
                    {% trans 'Open Note' %}
                </button>
            </div>

        </div>
        <!-- Modal window to display full note -->
        <div class="modal fade" id="noteModal{{ note.id }}" tabindex="-1"
             aria-labelledby="noteModalLabel{{ note.id }}" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="noteModalLabel{{ note.id }}">{{ note.text }}</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <p>{% trans 'Description' %}: {{ note.description }}</p>
                        <p>{% trans 'Tags' %}:
                            {% for tag in note.tags.all %}
                            <a href="?tag={{ tag.name }}">#{{ tag.name }}</a>{% if not forloop.last %}, {% endif %}
                            {% endfor %}
                        </p>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}